/**
 * Region shape type definitions
 *
 * Represents detected regions in documents (handwriting, stamps, signatures, etc.)
 * These are typically generated by document analysis systems.
 */

import type { Bounds } from "../../types/geometry";
import type { DrawShape } from "../common/registry";
import { generateShapeId } from "../common/registry";

/**
 * Metadata for detected regions
 */
export interface RegionMetadata {
  /** Classification group (e.g., "ink", "stamp", "signature") */
  group?: string;
  /** Specific kind within group (e.g., "handwriting", "rubber-stamp") */
  kind?: string;
  /** Human-readable label */
  label?: string;
  /** Detection confidence score (0-1) */
  confidence?: number;
  /** Text detected within the region */
  detectedText?: string;
  /** Whether the detected text is numeric */
  isNumeric?: boolean;
  /** Detected language code */
  language?: string;
}

/**
 * Region shape
 *
 * Represents a detected region with one or more bounding rectangles.
 * Similar to TextHighlightShape but includes detection metadata.
 */
export interface RegionShape extends DrawShape {
  type: "region";
  /** Bounding rectangles for the region */
  rects: Bounds[];
  /** Detection metadata */
  metadata?: RegionMetadata;
}

/**
 * Get bounding box of a region (combined bounds of all rects)
 */
export function getRegionBounds(shape: RegionShape): Bounds {
  if (shape.rects.length === 0) {
    return { x: 0, y: 0, width: 0, height: 0 };
  }

  let minX = Infinity;
  let minY = Infinity;
  let maxX = -Infinity;
  let maxY = -Infinity;

  for (const rect of shape.rects) {
    minX = Math.min(minX, rect.x);
    minY = Math.min(minY, rect.y);
    maxX = Math.max(maxX, rect.x + rect.width);
    maxY = Math.max(maxY, rect.y + rect.height);
  }

  return {
    x: minX,
    y: minY,
    width: maxX - minX,
    height: maxY - minY,
  };
}

/**
 * Create a region shape
 */
export function createRegionShape(
  rects: Bounds[],
  metadata?: RegionMetadata,
  id?: string
): RegionShape {
  return {
    id: id ?? generateShapeId(),
    type: "region",
    rects: rects.map((r) => ({ ...r })),
    style: {
      fill: "#FF9800",
      fillOpacity: 0.15,
      stroke: "#FF9800",
      strokeWidth: 2,
      blendMode: "multiply",
    },
    metadata,
  };
}
